### Урок 6. Системы линейных уравнений. Часть 1.

In [1]:
import numpy as np

#### Решить систему уравнений методом Гаусса:

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & -3 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

$\begin{cases}x_1 + x_2 - x_3 - 2x_4 = 0\\ -x_2 + x_3 + 5x_4 = -2 \\ x_3 - \frac{3}{2}x_4 = -2\end{cases}$

Получившаяся система имеет бесконечное число решений, т.к. $x_4$ может принимать любые значения, $x_4=c$

$\begin{cases} x_1= -x_2+x_3+2c\\ x_2=2+x_3+5c \\ x_3=-2+\frac{3}{2}c\end{cases}$

#### Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

$\begin{cases}
x_{1}=1, \\
x_{3}=3, \\
x_{2}=2;
\end{cases}$



In [2]:
a = np.array([[3, -1, 1],
             [2, -5, -3],
             [1, 1, -1]])

In [3]:
a_ex = np.array([[3, -1, 1, 4],
             [2, -5, -3, -17],
             [1, 1, -1, 0]])

In [4]:
print(f'Ранг матрицы коэфициентов: {np.linalg.matrix_rank(a)}')
print(f'Ранг расширенной матрицы: {np.linalg.matrix_rank(a_ex)}')

Ранг матрицы коэфициентов: 3
Ранг расширенной матрицы: 3


Система совместимая и имеет единственное решение

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

$\begin{cases}
0=5, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
0=11;
\end{cases}$

In [5]:
b = np.array([[2, -4, 6],
             [1, -2, 3],
             [3, -6, 9]])

In [6]:
b_ex = np.array([[2, -4, 6, 1],
             [1, -2, 3, -2],
             [3, -6, 9, 5]])

In [7]:
print(f'Ранг матрицы коэфициентов: {np.linalg.matrix_rank(b)}')
print(f'Ранг расширенной матрицы: {np.linalg.matrix_rank(b_ex)}')

Ранг матрицы коэфициентов: 1
Ранг расширенной матрицы: 2


Система несовместимая и не имеет решений

в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

$\begin{cases}
0=5, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
0=11;
\end{cases}$

In [8]:
c = np.array([[1, 2, 5],
             [3, 2, -8]])

In [9]:
c_ex = np.array([[1, 2, 5, 4],
             [3, 2, -8, -2]])

In [10]:
print(f'Ранг матрицы коэфициентов: {np.linalg.matrix_rank(c)}')
print(f'Ранг расширенной матрицы: {np.linalg.matrix_rank(c_ex)}')

Ранг матрицы коэфициентов: 2
Ранг расширенной матрицы: 2


Система совместимая и имеет бесконечное количество решений

#### Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$

In [11]:
a = np.array([[1, 3, -2, 4],
             [0, 5, 0, 1],
             [0, 0, 3, 0],
             [0, 0, 0, 2]])

In [12]:
a_ex = np.array([[1, 3, -2, 4, 3],
             [0, 5, 0, 1, 2],
             [0, 0, 3, 0, 4],
             [0, 0, 0, 2, 1]])

In [13]:
print(f'Ранг матрицы коэфициентов: {np.linalg.matrix_rank(a)}')
print(f'Ранг расширенной матрицы: {np.linalg.matrix_rank(a_ex)}')

Ранг матрицы коэфициентов: 4
Ранг расширенной матрицы: 4


Cистема совместима и имеет одно решение, т.к. ранг матрицы коэфициентов и расширеной матрицы совпадают и равны числу неизвестных

#### Дана система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

In [14]:
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [15]:
a_ex = np.array([[1, 2, 3, 1],
             [4, 5, 6, 2],
             [7, 8, 9, 4]])

In [16]:
print(f'Ранг матрицы коэфициентов: {np.linalg.matrix_rank(a)}')
print(f'Ранг расширенной матрицы: {np.linalg.matrix_rank(a_ex)}')

Ранг матрицы коэфициентов: 2
Ранг расширенной матрицы: 3


$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 7a
\end{matrix}
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
(4a-b)/3\\
c + a - 2b
\end{matrix}
\end{pmatrix}$

Система будет несовместной только при условии, если $c+a-2b \neq 0$

### Урок 7. Системы линейных уравнений. Часть 2.

#### Решить систему уравнений методом Крамера:

а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$det A = \begin{vmatrix}
1 & -2\\
3 & -4
\end{vmatrix} = -4 + 6 = 2$  

$det A_1 = \begin{vmatrix}
1 & -2\\
7 & -4
\end{vmatrix} = -4 + 14 = 10$  

$det A_2 = \begin{vmatrix}
1 & 1\\
3 & 7
\end{vmatrix} = 7 - 3 = 4$  

$x_1=\frac{det A_1}{det A}=5$  
$x_2=\frac{det A_2}{det A}=2$

In [17]:
a = np.array([[1,-2],[3,-4]])
a1 = np.array([[1,-2],[7,-4]])
a2 = np.array([[1,1],[3,7]])
print(f'х1 = {np.linalg.det(a1)/np.linalg.det(a):.0f}')
print(f'х2 = {np.linalg.det(a2)/np.linalg.det(a):.0f}')

х1 = 5
х2 = 2


б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$det A = \begin{vmatrix}
2 & -1 & 5\\
1 & 1 & -3\\
2 & 4 & 1
\end{vmatrix} = 2 + 6 + 20 + 24 + 1 - 10 = 43$

$det A_1 = \begin{vmatrix}
10 & -1 & 5\\
-2 & 1 & -3\\
1 & 4 & 1
\end{vmatrix} = 10 + 3 - 40 - 5 - 2 + 120 = 86$

$det A_2 = \begin{vmatrix}
2 & 10 & 5\\
1 & -2 & -3\\
2 & 1 & 1
\end{vmatrix} = -4 -60 +5 +20 -10 +6 = -43$

$det A_3 = \begin{vmatrix}
2 & -1 & 10\\
1 & 1 & -2\\
2 & 4 & 1
\end{vmatrix} = 2 + 4 + 40 - 20 + 1 + 16 = 43$

$x_1=\frac{det A_1}{det A}=2$  
$x_2=\frac{det A_2}{det A}=-1$  
$x_3=\frac{det A_3}{det A}=1$

In [18]:
b = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
b2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
b3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'х1 = {np.linalg.det(b1)/np.linalg.det(b):.0f}')
print(f'х2 = {np.linalg.det(b2)/np.linalg.det(b):.0f}')
print(f'х2 = {np.linalg.det(b3)/np.linalg.det(b):.0f}')

х1 = 2
х2 = -1
х2 = 1


#### Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

$U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 7 & 2\\
0 & 0 & 0 & 5
\end{pmatrix}$

$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 4 & 1 & 0\\
4 & 6 & 3 & 1
\end{pmatrix}$

#### Решить систему линейных уравнений методом $LU$-разложения

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$

$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & \frac{-23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$

$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 0 & \frac{52}{9}
\end{pmatrix}$

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{2} & 1
\end{pmatrix}$

$Ly=b$

$\begin{cases}
y_{1}=1, \\
\frac{11}{2}y_{1}+y_{2}=-6, \\
\frac{9}{2}y_{1}+ \frac{7}{2}y_{2}+y_{3}=-5.
\end{cases}$  
$y_{1} = 1,$  
$y_{2}=-6 -\frac{11}{2} =11.5$  
$y_{3}=-5-\frac{9}{2} - \frac{7}{2}=-13$

$y_{1}=1$

$y_{2}=-11.5$

$y_{3}= 30.75$

$Ux=y$

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
1.5x_{2}-11.5x_{3}=-11.5 \\
-20x_{3}=30.75
\end{cases}$

$x_1 = -1$

$\begin{cases}
2(-1)+3=1 \\
11(-1)+5=-6 \\
9(-1)+4=-5
\end{cases}$

#### Решить систему линейных уравнений методом Холецкого

$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

In [19]:
from numpy.linalg import cholesky
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
ch = cholesky(a)
print(ch)

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]


$Ly=b$

$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$

$L^{T}x=y:$

$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$  

$x_{1}=6,$  
$x_{2}=-5,$  
$x_{3}=-4.$

#### Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [21]:
#Минор
def submatrix(M,c):
    B = [[1]*len(M) for i in range(len(M))]
    for l in range(len(M)):
        for k in range(len(M)):
            B[l][k] = M[l][k]
    
    B.pop(0)
    
    for i in range(len(B)):
        B[i].pop(c)
    return B

#Определитель методом Лапласа
def det_L(M):
    X = 0
    if len(M) != len(M[0]):
        print('Матрица не квадратная')
    else:
        if len(M)<=2:
            return M[0][0] * M[1][1] - M[0][1] * M[1][0]
        else:
            for i in range(len(M)):
                X = X + ((-1)**i)*M[0][i]*det_L(submatrix(M,i))
        return X

#Решение методом Крамера
def Kramer(A,B):
    det_A = det_L(A)
    X = []
    if det_A == 0:
        print('Определитель матрицы не должен быть равен 0')
        return X
    n = len(A)    
    for i in range(n):
        matrix = A.copy()
        matrix[:,i] = B
        print('\n',matrix)
        X.append(det_L(matrix) / det_A)
    return X
    

a = np.array([[1,-2],[3,-4]])
b = np.array([1,7])
print(Kramer(a,b))


 [[ 1 -2]
 [ 7 -4]]

 [[1 1]
 [3 7]]
[5.0, 2.0]
